### ISSUE TITLE
com.webank.scaffold.exception.ScaffoldException: common  is not contract file

### ISSUE THREAD

**Issue by coda-fandom** [WeBankBlockchain/SmartDev-Scaffold#21]
如果我在tools/contracts里放一个带目录结构的合约，执行run.sh会把目录当成合约，并且报错：
```
4 actionable tasks: 4 executed
end compiling scaffold...
start generating demo...
com.webank.scaffold.exception.ScaffoldException: common  is not contract file
	at com.webank.scaffold.artifact.dir.ContractsDir.checkContractsDir(ContractsDir.java:62)
	at com.webank.scaffold.artifact.dir.ContractsDir.doGenerateSubContents(ContractsDir.java:46)
	at com.webank.scaffold.artifact.dir.DirectoryArtifact.generate(DirectoryArtifact.java:28)
	at com.webank.scaffold.artifact.dir.MainDir.doGenerateSubContents(MainDir.java:31)
	at com.webank.scaffold.artifact.dir.DirectoryArtifact.generate(DirectoryArtifact.java:28)
	at com.webank.scaffold.artifact.dir.SrcDir.doGenerateSubContents(SrcDir
```

**Comment by arc0035** [comment]
使用dev分支看下是否还有此问题？

**Comment by arc0035** [comment]
目前run.sh仅支持将contracts目录来作为sol文件的目录，若要手动指定目录，可以直接gradle shadowJar生成可执行jar包，并在-s选项中指定。

**Comment by arc0035** [comment]
目前run.sh仅支持将contracts目录来作为sol文件的目录，若要手动指定目录，可以直接gradle shadowJar生成可执行jar包，并在-s选项中指定。
